import random

palabras = ("Máximo Alva",
            "Marcos Menéndez",
            "Julián Grimblat",
            "Ciro Fernández",
            "Manuel Krivoy",
            "Lara Pino",
            "Maite Lukasiunas",
            "Augusto Tassi",
            "Juan Ignacio Rimada",
            "Ignacio Maragliano",
            "Zahir Jacob",
            "Valentín Dimenna",
            "Lucas Muggeri",
            "Gianfranco Peloni",
            "Francisco Gut",
            "Augusto Farías",
            "Patricio Tosti",
            "Ignacio Tosti",
            "Alan Escalante",
            "Alex Lorenth",
            "Lua Conechny",
            "Ulises Umansky",
            "Franco Riquelme",
            "Gianluca Bontempo",
            "Guadalupe De Lorenzi",
            "Milagros Gurgone",
            "Luciana Pumar",
            "Rosario Ghiglione",
            "Juliana Consolati",
            "Juan Bautista Figueredo",
            "Ignacio Moro",
            "Juan Burgués",
            "Guido Devoto",
            "Guadalupe Díaz",
            "Rosario González",
            "Juan Elías De Prinzio",
            "Juan Alonso",
            "Ignacio Roldán",
            "Ignacio Nogueras",
            "Morena Chiliutti",
            "Agustina Arias",
            "Sara Intelangelo",
            "Agustín Grandi",
            "Miguel Ortiz",
            "Rodrigo Marí",
            "Lautaro Teta Musa",
            "Agustín Luzzini",
            "Dante Manzini",
            "Ignacio Ferrari",
            "Jermías Tomás",
            "Felipe Sagarraga",
            "Patricio Sagarraga",
            "Violeta Briatore",
            "Valentina Luna",
            "Luciana Sabetti",
            "Camila Cia",
            "Matías Raimundez",
            "María Deheza",
            "Francisca Trabajo",
            "Mirko Dei Cas",
            "Valentina Parola",
            "Lara Spector",
            "Giulia Cardona",
            "María Victoria Coassin",
            "Ana Soldani",
            "Paula Koval",
            "Kayla Vázquez",
            "Marko Martín",
            "Martín Zega",
            "Santino Portesio",
            "Mauro Dorigoni",
            "Frank García",
            "Esteban Kuzmicich",
            "Bruno Leo Santi",
            "Judith Lacorte",
            "Martín Vázquez",
            "Franco Liserre",
            "Isabella Roccuzzo",
            "Julieta Manzanas",
            "Ramiro Aballay",
            "Lucas Buma",
            "Victoria Mallia",
            "María Emilia Destito",
            "Bruno Gardella",
            "Ariel Malvaso",
            "Ladislao Godocik",
            "Román Moyano",
            "Elián Mendoza",
            "Candela López",
            "Manuel Abraham",
            "Dino Francolini",
            "Francesco Mozzatti",
            "Luciano Visintini",
            "Matías Gurvich",
            "Mateo Lioi",
            "Alejo Melfi",
            "Julián Osuna",
            "Julieta Kil",
            "Sarina Manso",
            "Valentina Tarsitano",
            "Iñaki Ilincheta",
            "Nazareno Necchi",
            "Nicolás Welschen",
            "Leandro Negri",
            "Alan Cappello",
            "Sara Dellacasa",
            "Baltazar Díaz Moller",
            "Cecilia Contreras",
            "Melany Rathmann",
            "Lucila Carranza",
            "Gisel Pagán",
            "Juan Ignacio Pozzi",
            "Valentino Gambino",
            "Juan Palmieri",
            "Ilena Szumanski",
            "Matías Colombo",
            "Matías Estrada",
            "Francisco Vernetti",
            "Santiago Campanini",
            "Ignacio Roca",
            "Santiago Trujillo",
            "Leonel Domínguez",
            "Clarisa Franzini",
            "Juan Krapacher",
            "Marcos Arocena",
            "Manuel Retorta",
            "Olivia Ausili",
            "Gregorio García Mata",
            "Sebastián Giufre",
            "Federico Rojas",
            "Fiorella Carlini",
            "Álvaro Murga"
            )

def generar_partida(cant_jugadores: int, cant_impostores: int) -> list:
    """
    Genera una partida del juego del impostor.
    
    - cant_jugadores (int): número de jugadores
    - cant_impostores (int): número de impostores (menor a cant_jugadores).
    
    - return (list): lista con la palabra o 'Impostor' para cada jugador.
    """
    if cant_impostores >= cant_jugadores:
        raise ValueError("La cantidad de impostores debe ser menor a la de jugadores.")
    
    palabra = random.choice(palabras)
    impostores = random.sample(range(cant_jugadores), cant_impostores)
    
    asignacion = list()
    
    for i in range(cant_jugadores):
        if i in impostores:
            asignacion.append("Impostor")
        else:
            asignacion.append(palabra)
    
    return asignacion  